### ISSUE TITLE
[BUG] BOJ-extension 문제 검색기능이 작동하지 않음

### ISSUE THREAD

**Issue by i1hwan** [dltkdgns00/BOJ-extension#5]
BOJ-extension 1.1.1 버전과 1.1.0 버전에서 문제 검색 기능이 아래 오류를 출력하면서 작동하지 않습니다.
`Failed to fetch the problem: AxiosError: Request failed with status code 403`
1.0.3 버전으로 다운그레이드 할 시 잘 작동합니다.

**Comment by dltkdgns00** [comment]
안녕하세요! 혹시 몇번 문제였는지나 등등 버그당시 상황들에 대해 알려주실 수 있으신가요?

**Comment by i1hwan** [comment]
넵! 현재 개발환경은 github codespace에서 BOJ-extension을 설치하였고, 1.1.1 버전 기준 문제는 어떤것도 검색되지 않습니다... (ex: 1000번, 10250번 등)
마찬가지로 1.0.3 버전으로 다운그레이드시 잘 작동합니다.

**Comment by dltkdgns00** [comment]
네 오늘 확인해봤는데요.. 결론은 CORS 에러로 확인되었습니다.
1.1.1버전, 1.0.3버전 1.0.3버전의 바로 다음 커밋에 있는 문제를 찾아내는 함수에 대해서 테스트를 해봤습니다.
테스트환경은 로컬, 깃허브 스페이스, vscode ssh를 통한 원격 워크스페이스 세 곳에서 테스트를 진행했는데요

로컬, 원격 워크스페이스에서는 함수가 전부 잘 작동하는 것을 확인할 수 있었지만, 깃허브 코드스페이스에서는 403에러로 오류가 발생하는 것을 확인할 수 있었습니다. 심지어 종종 1.0.3버전에서도 오류가 발생했습니다.
함수만 별개로 파일을 만들어서 ts-node를 사용해 파일을 실행시켰을때는 깃허브 코드스페이스에서도 잘 작동했지만 vscode확장으로서는 작동하지 않았습니다.

결론: BOJ-extension 확장의 경우 BOJ 공식 확장이 아니고, 문제를 가져올 때 웹 스크래핑을 진행하다보니 CORS에러가 발생할 수 있습니다. 깃허브 코드스페이스에선 CORS에러가 자주 발생하니 사용이 불가할 것 같습니다.

어떤 이유에서 코드스페이스를 사용하셨는지는 모르겠지만 ssh를 활용한 원격 워크스페이스를 사용해보심이 어떠시온지..

감사합니다.

**Comment by i1hwan** [comment]
현재 복무중이라... 사지방에서는 이 방식으로 코딩하는게 제일 쉬워서 코드스페이스를 사용했습니다.
이참에 외부서버에 code-server를 설치하고 BOJ-extension도 설치해보았는데 1.0.3 버전과 1.1.1 버전 모두 잘 작동하는걸 확인했습니다.

앞으로도 지속적인 업데이트 부탁드립니다. 감사합니다!
