### ISSUE TITLE
push 질문입니다

### ISSUE THREAD

**Issue by mlnho** [dltkdgns00/BOJ-extension#8]
token 생성 후 해당 레포에 action을 달아뒀습니다.

이후 코드 작성 후 push 하는데 github에 푸쉬 실패했다고 뜹니다.

자동 push를 위한 자세한 방법을 알고 싶어서 이렇게 글을 남깁니다.

**Comment by mlnho** [comment]
workflow.yml 에서 token 부분에 context access might be invalied: GH_TOKEN 이라고 뜹니다.

**Comment by dltkdgns00** [comment]
푸시 이후 깃허브 액션에서 오류가 난다는 말씀이신거죠?

**Comment by mlnho** [comment]
github에 푸쉬하는데 실패했습니다.

라고 오른쪽 하단에 뜹니다 ㅠ

**Comment by dltkdgns00** [comment]
<img width="1190" alt="스크린샷 2024-09-02 오후 11 11 36" src="https://github.com/user-attachments/assets/deb540db-2aa4-4a42-9c1e-78688445b69c">
제 레포지토리를 예시로 보여드리면
이런식으로 GH_TOKEN이라는 이름의 secret variable이 있어야 합니다. 내용은 깃허브 토큰이 되구요

**Comment by dltkdgns00** [comment]
아 그렇다면 vscode상에서 깃허브 푸시가 안된다는 말씀이신거죠?

**Comment by mlnho** [comment]
네,,  vscode에서 BOJ:push to github 햇는데 그렇습니다 ㅠ

**Comment by mlnho** [comment]
<img width="1216" alt="스크린샷 2024-09-02 오후 11 12 54" src="https://github.com/user-attachments/assets/9d7e15db-20fd-44fb-8c38-a97ba0c5a5fb">


저도 이렇게 만들긴햇는데 ㅠ

**Comment by mlnho** [comment]
저 토큰을 따로 어디에 작성해야하는건가요?? 아님 따로 추가적인 설정을 해야하나요?? 맥북환경입니다

**Comment by dltkdgns00** [comment]
현재 폴더의 깃 원격저장소가 어떻게 되시나요?

**Comment by mlnho** [comment]
아 따로 원격저장소 설정을 안해줫는데 ,,, 안해줘서 그런건가요? ㅠ

**Comment by dltkdgns00** [comment]
`git remote -v`
쳐보시겠어요?

**Comment by mlnho** [comment]
origin  https://github.com/mlnho/python.git (fetch)
origin  https://github.com/mlnho/python.git (push)

d이렇게 뜹니당 ㅠ

**Comment by dltkdgns00** [comment]
현재 BOJ-extension에서 지원하는 push 기능은 단순 pull, add, commit, push 기능이기때문에 현재 워크스페이스폴더에서의 git 설정을 따라갑니다. 직접 pull commit push 를 해보시고 문제가 있는지 확인해보시겠어요?

**Comment by mlnho** [comment]
아 감사합니다 ㅠㅠ 해결완료햇습니다 ㅠㅠㅠ

**Comment by mlnho** [comment]
궁금한게 백준사이트에 제출 기록을 남길 수는 없는건가요?!!? 이건 따로 백준사이트에서 제출을 해야하는건가요?

**Comment by dltkdgns00** [comment]
자동으로 백준 사이트에 제출하는 기능은 없냐고 물으시는거죠?
결론부터 말씀드리자면 그 기능은 탑재되어있지 않습니다.
예전에는 브라우저가 아닌 다른 클라이언트에서도 백준에 로그인이 가능해 자동을 제출까지 가능한 확장들이 있었습니다.
제 확장보다 이전에 배포된 다른 vscode확장들을 보시면 그 흔적이 남아있습니다.
하지만 최근 몇년 안에 백준에 reCaptcha가 적용되면서 브라우저에서 직접 로그인을 하는 수 밖에 없게 되었습니다.

저도 확장 개발당시 자동 제출까지 가능토록 하고 싶었지만 그러한 문제 때문에 개발하지 못하였습니다.

BOJ-extension을 사용해주셔서 감사합니다.
앞으로도 많은 이용 바랍니다🙂
